name: integration

on:
  push:
    branches: [ master, main ]

jobs:
  integration:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: golang:1.19-bullseye
      env:
        FOO: Bar
        REVISION: $GITHUB_SHA
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: | 
          echo "$GITHUB_SHA should match the commit ID of feature branch"
          echo "github.sha -> ${{ github.sha }}"
          echo "GITHUB_SHA -> $GITHUB_SHA"
          make REVISION=${{ github.sha }} PAT=${{ secrets.GITHUB_TOKEN }} build_ci
      - name: release
        run: |
          make REVISION=$GITHUB_SHA tag
          make REVISION=${{ github.sha }} PAT=${{ secrets.GITHUB_TOKEN }} release