name: integration

on:
  push:
    branches: [ master, main ]

jobs:
  release:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: golang:1.19-bullseye
      env:
        FOO: Bar
        REVISION: $GITHUB_SHA
    steps:
      - uses: actions/checkout@v3
      - name: pre-requisites
        run: |
          mkdir -p ~/bin
          curl -L -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x ~/bin/jq
          export PATH=$PATH:~/bin
          jq --version
      - name: build
        run: | 
          echo "$GITHUB_SHA should match the commit ID of feature branch"
          echo "github.sha -> ${{ github.sha }}"
          echo "GITHUB_SHA -> $GITHUB_SHA"
          make REVISION=${{ github.sha }} PAT=${{ secrets.GITHUB_TOKEN }} build_ci
      - name: publish
        run: |
          make REVISION=$GITHUB_SHA tag
          ls -lat seeder/dist/*
          make REVISION=${{ github.sha }} PAT=${{ secrets.GITHUB_TOKEN }} release
